version: "3"
services:
  broker:
    image: rmohr/activemq:5.10.0
    ports:
      - 8161:8161 #UI
      - 5672:5672 #AMQP
  frontend-chat:
    image: cmd-chat:0.0.1-SNAPSHOT
    labels:
      - traefik.http.routers.chat.rule=Host(`localhost`) && PathPrefix(`/chat`)
      - traefik.http.middlewares.chat.stripprefix.prefixes=/chat
      - traefik.http.routers.chat.middlewares=chat@docker
      - traefik.http.services.chat.loadbalancer.server.port=8080
  api-write:
    image: b-write-api:0.0.1-SNAPSHOT
    labels:
      - traefik.http.routers.write.rule=Host(`localhost`) && PathPrefix(`/write`)
      - traefik.http.middlewares.write.stripprefix.prefixes=/write
      - traefik.http.routers.write.middlewares=write@docker
      - traefik.http.services.write.loadbalancer.server.port=8080
  api-read:
    image: b-read-api:0.0.1-SNAPSHOT
    labels:
      - traefik.http.routers.read.rule=Host(`localhost`) && PathPrefix(`/read`)
      - traefik.http.middlewares.read.stripprefix.prefixes=/read
      - traefik.http.routers.read.middlewares=read@docker
      - traefik.http.services.read.loadbalancer.server.port=8080
  domain-handler:
    image: b-domain-handler:0.0.1-SNAPSHOT
  event-source:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: aoeu',.p;qjk
      POSTGRES_DB: event-source
  reverse-proxy:
    image: traefik:v2.1
    command: --api.insecure=true --providers.docker --accesslog=true
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
